version: "3.9"
services:
  db:
    image: db
    restart: always
    container_name: db
    build:
      context: .
      target: db
    environment:
      - POSTGRES_DB=srealitydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: ./app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
